name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # At minute 0 past every 3rd hour
    # https://crontab.guru/every-3-hours
    - cron: '0 */3 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dothanhlong.org/feed/"
          max_post_count: 10
