name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # every-day at 00:00
    # https://crontab.guru/every-day
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://s1.dothanhlong.org:10025/myblogfeed"
          # feed_list: "https://dothanhlong.org/sitemap.xml"
          max_post_count: 15
