name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # every-day at 00:00
    # https://crontab.guru/every-day
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
