name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 3rd hour
    # https://crontab.guru/every-3-hours
    - cron: "0 */3 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
